/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KatalogIndexRouteImport } from './routes/katalog/index'
import { Route as KatalogSlugRouteImport } from './routes/katalog/$slug'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogIndexRoute = KatalogIndexRouteImport.update({
  id: '/katalog/',
  path: '/katalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogSlugRoute = KatalogSlugRouteImport.update({
  id: '/katalog/$slug',
  path: '/katalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog': typeof KatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/katalog/$slug': typeof KatalogSlugRoute
  '/katalog/': typeof KatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontak' | '/tentang' | '/katalog/$slug' | '/katalog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontak' | '/tentang' | '/katalog/$slug' | '/katalog'
  id: '__root__' | '/' | '/kontak' | '/tentang' | '/katalog/$slug' | '/katalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontakRoute: typeof KontakRoute
  TentangRoute: typeof TentangRoute
  KatalogSlugRoute: typeof KatalogSlugRoute
  KatalogIndexRoute: typeof KatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/': {
      id: '/katalog/'
      path: '/katalog'
      fullPath: '/katalog/'
      preLoaderRoute: typeof KatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog/$slug': {
      id: '/katalog/$slug'
      path: '/katalog/$slug'
      fullPath: '/katalog/$slug'
      preLoaderRoute: typeof KatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontakRoute: KontakRoute,
  TentangRoute: TentangRoute,
  KatalogSlugRoute: KatalogSlugRoute,
  KatalogIndexRoute: KatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
